// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables with helpful error messages
if (!SUPABASE_URL || SUPABASE_URL === 'your-project-url-here' || SUPABASE_URL.includes('your-project')) {
  console.error('❌ SUPABASE_URL is not configured correctly!');
  console.error('Current value:', SUPABASE_URL || '(undefined)');
  console.error('\n📝 Please create a .env file in Frontend/Kllinic/ with:');
  console.error('VITE_SUPABASE_URL=https://xmhwyvojwukgowbhqhpo.supabase.co');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY=your-actual-anon-key');
  console.error('\n🔗 Get your keys from: https://supabase.com/dashboard/project/xmhwyvojwukgowbhqhpo/settings/api');
  console.error('\n⚠️ Then restart your development server (npm run dev)');
  
  throw new Error(
    `Invalid Supabase URL: "${SUPABASE_URL || '(missing)'}"\n` +
    `Please create a .env file with your actual Supabase credentials.\n` +
    `See console for detailed instructions.`
  );
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'your-anon-key-here' || SUPABASE_PUBLISHABLE_KEY.includes('your-anon')) {
  console.error('❌ SUPABASE_PUBLISHABLE_KEY is not configured correctly!');
  console.error('Current value:', SUPABASE_PUBLISHABLE_KEY ? '(placeholder text)' : '(undefined)');
  console.error('\n📝 Please update your .env file with your actual anon key');
  console.error('🔗 Get your key from: https://supabase.com/dashboard/project/xmhwyvojwukgowbhqhpo/settings/api');
  console.error('\n⚠️ Then restart your development server (npm run dev)');
  
  throw new Error(
    `Invalid Supabase API Key: Please update your .env file with your actual credentials.\n` +
    `See console for detailed instructions.`
  );
}

// Validate URL format
try {
  new URL(SUPABASE_URL);
} catch (e) {
  throw new Error(
    `Invalid Supabase URL format: "${SUPABASE_URL}"\n` +
    `URL must be a valid HTTP/HTTPS URL (e.g., https://your-project.supabase.co)`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});